# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable sleep mode to save battery
CONFIG_ZMK_SLEEP=y

# Sleep after 15 minutes of inactivity
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ZMK Studio - Interface graphique pour configuration en temps réel
CONFIG_ZMK_STUDIO=y

CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment to enable logging
# CONFIG_ZMK_USB_LOGGING=y
